'use client'

/* ElevenLabs Audio Native — a narrated reading of the paper, docked.

   It floats bottom-right rather than sitting at the top of the article, so it
   can be started or paused from anywhere in a long paper. Three things are
   handled here rather than left to the embed:

   1. The helper script is only fetched once the reader opens the dock. It is a
      third-party request on a page whose whole point is that it deploys as
      static output; paying for it on first paint would be a regression.
   2. The container reserves the player's declared height, so the injected
      iframe cannot shift anything when it arrives.
   3. Once mounted, the player stays mounted. Collapsing the dock hides it
      visually but never unmounts it, because unmounting would stop playback —
      the one thing a reader who pressed play does not want. */

import Script from 'next/script'
import { useEffect, useState } from 'react'
import { Icon } from '@/components/icons'
import { play } from '@/lib/sound'

const PUBLIC_USER_ID =
  '4257fc80837cbfd07c2336b31b3487cc6aafe42a4dc10ce122ff5b175398ff9b'

const HEIGHT = 90

export function AudioNative({ label = 'Listen' }: { label?: string }) {
  const [open, setOpen] = useState(false)
  // Separate from `open`: once the script has been requested we keep the player
  // alive across collapses so audio survives. Set from the event that opens the
  // dock rather than from an effect on `open` — an effect would render twice on
  // the first open, and mounting is a consequence of the click, not of the state.
  const [mounted, setMounted] = useState(false)

  // Escape closes the dock, which is what a floating panel over text should do.
  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false) }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open])

  return (
    <div className="audio-dock no-print">
      <div
        className="audio-panel"
        data-open={open ? 'true' : 'false'}
        aria-hidden={!open}
        id="audio-dock-panel"
      >
        <div
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            gap: '0.5rem', padding: '0.5rem 0.5rem 0.5rem 0.75rem',
            borderBottom: 'var(--rule)', background: 'var(--bg-sunken)',
          }}
        >
          <span className="label" style={{ fontSize: '0.75rem' }}>Narration</span>
          <button
            type="button"
            className="btn"
            aria-label="Close narration player"
            onClick={() => { setOpen(false); play('toggle') }}
            style={{ minHeight: 28, padding: '0 0.5rem', boxShadow: 'none' }}
          >
            <Icon name="cross" size={14} />
          </button>
        </div>

        <div style={{ minHeight: HEIGHT }}>
          {mounted ? (
            <>
              <div
                id="elevenlabs-audionative-widget"
                data-height={String(HEIGHT)}
                data-width="100%"
                data-frameborder="no"
                data-scrolling="no"
                data-publicuserid={PUBLIC_USER_ID}
                data-playerurl="https://elevenlabs.io/player/index.html"
              >
                <span className="meta" style={{ display: 'block', padding: '1rem' }}>
                  Loading the{' '}
                  <a href="https://elevenlabs.io/text-to-speech" target="_blank" rel="noopener noreferrer">
                    ElevenLabs Text to Speech
                  </a>{' '}
                  AudioNative player…
                </span>
              </div>
              <Script src="https://elevenlabs.io/player/audioNativeHelper.js" strategy="lazyOnload" />
            </>
          ) : null}
        </div>

        <p className="caption" style={{ padding: '0 0.75rem 0.625rem', margin: '0.5rem 0 0', fontSize: '0.6875rem' }}>
          Generated by ElevenLabs from this page. The tables and figures are only
          in the written editions.
        </p>
      </div>

      <button
        type="button"
        className="btn"
        aria-expanded={open}
        aria-controls="audio-dock-panel"
        onClick={() => { setOpen((v) => !v); setMounted(true); play('toggle') }}
        style={{ boxShadow: 'var(--shadow-lifted)', borderRadius: 999 }}
      >
        <Icon name={open ? 'cross' : 'soundOn'} size={16} />
        {open ? 'Hide' : label}
      </button>
    </div>
  )
}
