/* GENERATED by tools/qr.mjs — do not edit by hand.
   Encodes https://zero.khe.money at error-correction level H.
   Paths use currentColor so the mark inverts with the theme and prints black. */

export const QR_URL = 'https://zero.khe.money'

export function QrCode({ size = 104, title = 'QR code linking to zero.khe.money' }: {
  size?: number
  title?: string
}) {
  return (
    <svg
      viewBox="0 0 29 29"
      width={size}
      height={size}
      role="img"
      aria-label={title}
      shapeRendering="crispEdges"
      style={{ display: 'block', color: 'var(--text)' }}
    >
      <title>{title}</title>
      <path fill="none" d="M0 0h29v29H0z"/><path stroke="currentColor" d="M0 0.5h7m3 0h4m2 0h4m2 0h7M0 1.5h1m5 0h1m4 0h2m1 0h1m1 0h3m1 0h1m1 0h1m5 0h1M0 2.5h1m1 0h3m1 0h1m1 0h1m2 0h2m1 0h2m2 0h1m1 0h1m1 0h1m1 0h3m1 0h1M0 3.5h1m1 0h3m1 0h1m1 0h2m1 0h2m1 0h2m1 0h1m1 0h1m2 0h1m1 0h3m1 0h1M0 4.5h1m1 0h3m1 0h1m2 0h1m2 0h2m3 0h3m2 0h1m1 0h3m1 0h1M0 5.5h1m5 0h1m2 0h1m6 0h3m1 0h1m1 0h1m5 0h1M0 6.5h7m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m1 0h7M9 7.5h1m2 0h1m2 0h1m3 0h1M3 8.5h2m1 0h2m1 0h1m3 0h2m1 0h1m1 0h2m5 0h2M2 9.5h1m1 0h1m3 0h2m1 0h3m1 0h2m3 0h1m2 0h2m2 0h1M2 10.5h2m1 0h2m1 0h4m2 0h2m1 0h1m3 0h2m1 0h2M3 11.5h2m2 0h1m1 0h1m1 0h1m2 0h2m1 0h2m6 0h1m2 0h1M1 12.5h1m4 0h1m1 0h2m1 0h2m1 0h1m3 0h1m1 0h3m2 0h1m1 0h1M0 13.5h1m1 0h3m2 0h1m3 0h7m4 0h1m1 0h1m1 0h1m1 0h1M1 14.5h1m2 0h1m1 0h1m3 0h4m1 0h1m1 0h3m3 0h1m1 0h1m2 0h1M4 15.5h2m1 0h3m1 0h1m1 0h1m1 0h3m1 0h3m2 0h3M4 16.5h3m1 0h1m1 0h2m1 0h2m4 0h1m3 0h1m1 0h1m2 0h1M0 17.5h1m1 0h1m5 0h1m1 0h1m1 0h2m5 0h2m3 0h1m1 0h1M0 18.5h4m2 0h2m4 0h1m1 0h1m3 0h2m3 0h1m1 0h2m1 0h1M0 19.5h3m1 0h1m3 0h1m2 0h3m1 0h1m1 0h3m1 0h3m2 0h1m1 0h1M0 20.5h2m2 0h3m1 0h2m4 0h1m2 0h1m1 0h8m1 0h1M8 21.5h2m1 0h2m4 0h1m1 0h2m3 0h3M0 22.5h7m1 0h1m1 0h1m3 0h1m1 0h5m1 0h1m1 0h1m1 0h2M0 23.5h1m5 0h1m3 0h3m2 0h1m1 0h1m1 0h2m3 0h2m1 0h1M0 24.5h1m1 0h3m1 0h1m1 0h1m2 0h1m1 0h5m1 0h6M0 25.5h1m1 0h3m1 0h1m1 0h3m3 0h2m1 0h2m4 0h1m2 0h2M0 26.5h1m1 0h3m1 0h1m4 0h1m1 0h2m5 0h2m1 0h2m2 0h2M0 27.5h1m5 0h1m2 0h1m1 0h1m3 0h2m4 0h1m2 0h1m1 0h1m1 0h1M0 28.5h7m3 0h2m3 0h1m2 0h7"/>
    </svg>
  )
}
