#!/usr/bin/env node
/* Generate the QR code as a static SVG committed to the repo.

   Generated once rather than at runtime so the published page carries no QR
   dependency, and so the same vector lands in both the web page and the PDF.
   It uses currentColor, which lets it invert with the theme for free. */

import QRCode from 'qrcode'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// Resolve against this file, not the cwd: the qrcode dependency lives in
// web/node_modules, so the script is invoked from web/ but writes to web/components.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const URL = process.argv[2] ?? 'https://zero.khe.money'
const OUT = join(ROOT, 'web', 'components', 'qr-code.tsx')

// High error correction: printed on paper, the code has to survive a scuff.
const svg = await QRCode.toString(URL, {
  type: 'svg',
  errorCorrectionLevel: 'H',
  margin: 0,
  width: 256,
})

// Strip the generator's own fill colours so the mark inherits currentColor and
// works on either canvas without a second asset.
const body = svg
  .replace(/<\?xml[^>]*\?>/, '')
  .replace(/<svg[^>]*>/, '')
  .replace(/<\/svg>/, '')
  .replace(/fill="#ffffff"/gi, 'fill="none"')
  .replace(/fill="#000000"/gi, 'fill="currentColor"')
  /* The dark modules are drawn as a stroked path, not a filled one, so
     rewriting `fill` alone leaves a literal #000000 in the committed file —
     invisible against the dark canvas the page authors first. */
  .replace(/stroke="#ffffff"/gi, 'stroke="none"')
  .replace(/stroke="#000000"/gi, 'stroke="currentColor"')
  .replace(/shape-rendering="crispEdges"/gi, '')
  .trim()

/* Nothing below may carry a literal colour: the page's monochrome rule is that
   every colour comes from a CSS variable, and here that means currentColor. */
const literal = body.match(/(?:fill|stroke)="(?!none|currentColor)[^"]*"/gi)
if (literal) {
  throw new Error(`qr.mjs: unhandled literal colour in generated SVG: ${literal.join(', ')}`)
}

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 33 33'

const file = `/* GENERATED by tools/qr.mjs — do not edit by hand.
   Encodes ${URL} at error-correction level H.
   Paths use currentColor so the mark inverts with the theme and prints black. */

export const QR_URL = '${URL}'

export function QrCode({ size = 104, title = 'QR code linking to ${URL.replace(/^https?:\/\//, '')}' }: {
  size?: number
  title?: string
}) {
  return (
    <svg
      viewBox="${viewBox}"
      width={size}
      height={size}
      role="img"
      aria-label={title}
      shapeRendering="crispEdges"
      style={{ display: 'block', color: 'var(--text)' }}
    >
      <title>{title}</title>
      ${body}
    </svg>
  )
}
`

mkdirSync(join(ROOT, 'web', 'components'), { recursive: true })
writeFileSync(OUT, file)
console.log(`wrote ${OUT}`)
console.log(`encodes ${URL}, viewBox ${viewBox}, ${body.length} bytes of path data`)
